### ISSUE TITLE
windows support?

### ISSUE THREAD

**Issue by MemorableUsername1** [SamueleAmato/Instagram-Hacking-Toolkit#8]
pip 3 is not recognized what do i do (what is pip3)

**Comment by MemorableUsername1** [comment]
once this issue is resolved (if it is one)
id like to know basically exactly what to do after (not very experienced in python sorry just trying to get in an old account of mine or get it removed)

**Comment by SamueleAmato** [comment]
Windows support has been removed (due to huge bugs), the feature will be implemented again in the next version (0.3.1); there was already Windows support in old versions (which has been removed in this version) however until the new version comes out you can always download an old one with Windows support > https://github.com/SamueleAmato/Instagram-Hacking-Toolkit/releases/download/0.2.0/Windows.zip
Tradotto con DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation
